
<?php $__env->startSection('content'); ?>
<div class="page-head"><div><h2>My Tasks</h2><p>Manage, search, edit and delete your database tasks.</p></div><a class="btn" href="<?php echo e(route('tasks.create')); ?>">+ Create Task</a></div>
<form class="card filters" method="GET"><input class="input" name="search" value="<?php echo e(request('search')); ?>" placeholder="Search task..."><select class="select" name="priority"><option value="">All Priority</option><?php $__currentLoopData = ['Low','Medium','High']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $p): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($p); ?>" <?php if(request('priority')==$p): echo 'selected'; endif; ?>><?php echo e($p); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select><select class="select" name="status"><option value="">All Status</option><?php $__currentLoopData = ['Pending','In Progress','Completed']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $s): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($s); ?>" <?php if(request('status')==$s): echo 'selected'; endif; ?>><?php echo e($s); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select><button class="btn">Search</button></form>
<?php $__empty_1 = true; $__currentLoopData = $tasks; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $task): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
<div class="task-card"><div><h3 class="task-title"><?php echo e($task->title); ?></h3><p class="task-desc"><?php echo e($task->description); ?></p></div><div class="badges"><span class="badge"><?php echo e($task->category); ?></span><span class="badge <?php echo e(strtolower($task->priority)); ?>"><?php echo e($task->priority); ?></span><span class="badge <?php echo e(str_replace(' ','-',strtolower($task->status))); ?>"><?php echo e($task->status); ?></span><span class="badge"><?php echo e($task->due_date?->format('Y-m-d') ?? 'No Date'); ?></span><a class="btn secondary" href="<?php echo e(route('tasks.edit',$task)); ?>">Edit</a><form method="POST" action="<?php echo e(route('tasks.destroy',$task)); ?>" onsubmit="return confirm('Delete this task?')"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="btn danger">Delete</button></form></div></div>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?> <div class="card"><h2>No tasks yet</h2><p style="color:#94a3b8">Create your first task to start organizing your work.</p></div><?php endif; ?>
<div style="margin-top:20px"><?php echo e($tasks->links()); ?></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.premium', ['title' => 'Tasks'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH D:\XAMP\htdocs\todo-premium\resources\views/tasks/index.blade.php ENDPATH**/ ?>